Repository aramexxsunburst/aramexx-sunburst, pull requests merged in 2018-03, with the labels that each got.

#3 Closes #1.
  .gitignore
  as/as/__init__.py
  as/as/settings.py
  as/as/urls.py
  as/as/wsgi.py
  as/manage.py
  sunburst/__init__.py
  sunburst/admin.py
  sunburst/apps.py
  sunburst/migrations/__init__.py
  sunburst/models.py
  sunburst/tests.py
  sunburst/views.py
Labels: enhancement

#4 Travis Integration added.
  .travis.yml
  Pipfile
  Pipfile.lock
Labels: enhancement

#6 Add heroku app.
  .gitignore
  terraform/heroku.tf
Labels: enhancement, integration

#8 Deployed to Heroku.
  .gitignore
  Pipfile
  Pipfile.lock
  Procfile
  as/as/settings.py
  bin/create
  readme.md
Labels: deploy

#12 Closes #11
  .travis.yml
  Pipfile
  Pipfile.lock
  aramexx/aramexx/__init__.py
  aramexx/aramexx/settings.py
  aramexx/aramexx/urls.py
  aramexx/aramexx/wsgi.py
  aramexx/manage.py
  aramexx/sunburst/__init__.py
  aramexx/sunburst/admin.py
  aramexx/sunburst/apps.py
  aramexx/sunburst/migrations/__init__.py
  aramexx/sunburst/models.py
  aramexx/sunburst/templates/sunburst/index.html
  aramexx/sunburst/tests/test_views.py
  aramexx/sunburst/views.py
  bin/create
  bin/local
  readme.md
  sunburst/tests.py
  sunburst/views.py
  terraform/docker.tf
  xml/example.xml
Labels: deploy, integration

#19 Upload file works.
  aramexx/aramexx/urls.py
  aramexx/sunburst/templates/sunburst/base.html
  aramexx/sunburst/templates/sunburst/index.html
  aramexx/sunburst/templates/sunburst/upload.html
  aramexx/sunburst/views.py
  as/as/__init__.py
  as/as/wsgi.py
  as/manage.py
  readme.md
  static/xml/example.xml
Labels: feature
